### ISSUE TITLE
[DeepAttack] - [daqiezi] - [Submission failed]

### ISSUE THREAD

**Issue by HqingLiu** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#11]
Dear Organizing Committee,

We would like to bring to your attention that in our last seven submission attempts, five were unsuccessful due to network failures. Despite ensuring a strong and stable network connection, we still encountered issues close to the completion of the submission process. Therefore, we kindly request that you reconsider the criteria for counting submission attempts and not count failed submissions due to network issues as successful ones.

We appreciate your understanding and assistance in this matter.

Thank you very much!

**Comment by aisg-py** [comment]
Thank you for raising this issue. However, as per Clause 15 of the Terms and Conditions, and to ensure fairness for all participants, we do not reset the submission count due to network connectivity issues. We appreciate your understanding.
