### ISSUE TITLE
[ModelCrackers] - [nonstop] - [Request for log file]

### ISSUE THREAD

**Issue by nonstopfor** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#12]
We kindly request the log file for our 1st submission (sub1.tar.gz), due to the SysError encountered. It would help us debug and build the correct submission files, thank you!

**Comment by nonstopfor** [comment]
Is there any update? Thanks!

**Comment by aisg-py** [comment]
Thank you for your request. Unfortunately, we are unable to release the log file for your 1st submission as it was outputting information that would compromise the hidden nature of the vLLM.

Additionally, your submission encountered an "Input File Format Error - Max Token Length Exceeded" error. We recommend reviewing your input files to ensure they adhere to the specified token limits.

Please let us know if you need further assistance.

**Comment by nonstopfor** [comment]
Thanks. We have fixed the length issue and made a new submission (sub2.tar.gz) but we still encounter the SysError. Could you please help send us the log file (you could remove any debug information that may compromise the hidden nature) or tell us the detailed error? Thanks a lot!

**Comment by aisg-py** [comment]
We have sent the log file to the teams.

**Comment by nonstopfor** [comment]
Thanks a lot. We note that the sent log file doesn't contain any error information such as "Input File Format Error - Max Token Length Exceeded". So we couldn't know where the SysError comes from according to this log file. Could you help check where the SysError comes from? Thank you so much!

**Comment by aisg-py** [comment]
We have reviewed the earlier submission. Kindly note some of your team’s attack prompt token lengths still exceed the 256 token length limit.

**Comment by nonstopfor** [comment]
Thanks a lot!
