### ISSUE TITLE
[DeepAttack] - [daqiezi] - [API Question]

### ISSUE THREAD

**Issue by HqingLiu** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#13]
Can we call all model APIs during the attack and get the returned response?

**Comment by aisg-py** [comment]
The competition set-up allows for participants' models to obtain the returned response. However, if the returned response from the VLLM is sent to stderr/log, we would not release that particular log file as this would compromise the hidden nature of the VLLM.
 
Kindly note the attacks should be conducted sequentially to different models, not in parallel.
