### ISSUE TITLE
[DeepAttack] - [daqiezi] - [Submission count issue]

### ISSUE THREAD

**Issue by HqingLiu** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#15]
Why did our submission count only update once today? Shouldn't it be updated 7 times over a 14-day period?

**Comment by aisg-py** [comment]
The team should be able to proceed with your 8th submission today. As per [Clause 7F of the Terms and Conditions,](https://gcss.aisingapore.org/terms-and-conditions) the team will be able to submit a maximum of 1 time **per day** over a rolling 2 week window.
