### ISSUE TITLE
[ateam] - [eyuansu62] - [Log File Request]

### ISSUE THREAD

**Issue by HamLaertes** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#17]
Hi, could you please share us with the log file of our latest submission due to the SysError encountered?

**Comment by aisg-py** [comment]
We have emailed the team the log file.

**Comment by HamLaertes** [comment]
Hi, 

we have corrected the bugs but still encounter SysError, would you please send us the log file of the latest submission? 
@aisg-py 

Thanks!

**Comment by aisg-py** [comment]
Sure, we have emailed the team the new log file.

**Comment by HamLaertes** [comment]
Received.
We have further shortened our prompt and still encounter a SysError.
Do the SysError still the "Input File Format Error - Max Token Length Exceeded"?

Thanks!

**Comment by aisg-py** [comment]
Yes, it is the same error.

**Comment by HamLaertes** [comment]
Okay, we have add one function to check the token length and if it exists the maximun length we will do nothing but return the benign prompt directly.

But still have the SysError....
Do the SysError still the "Input File Format Error - Max Token Length Exceeded"?

**Comment by aisg-py** [comment]
Based on the log file, the wrong host is used.

**Comment by HamLaertes** [comment]
We follow the exactly code in the `sample_submission/main.py` to interact with the backend server.
Would you please help us to figure out where we have the error?

Here is the code we post the request to the host:
```
def post_token_length_request(prompt):
    """Check the length of the prompt"""

    try:
        response = requests.post(
            GCSS_SERVER + "/attack_prompt/token_length", json={"prompt": prompt}
        )

        return response.json()
    except Exception as e:
        sys.stderr.write(f"{type(e)}: {e}")
        raise e
```

and Here is the definition of GCSS_SERVER (no change to the sample_submission/env_setup.py)
```
import os

# Environment Variables
GCSS_SERVER_CONTAINER_NAME = os.getenv(
    "GCSS_SERVER_CONTAINER_NAME", "vllm_server"
)
GCSS_SERVER = f"http://{GCSS_SERVER_CONTAINER_NAME}"
```

and Here is how we call the function
```
check_token_length_response = post_token_length_request(
            prompt_attack
        )
```
Why we have the wrong host?

**Comment by aisg-py** [comment]
The sample submission assumes that one is running a local sample of the Victim Model server for testing.
As noted in [https://github.com/AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#victim-models](https://github.com/AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#victim-models), you must read the environment variable `GCSS_SERVER` to obtain the host name in the competition server.

As a final note, this should be split off into a new issue since it is not related to the initial request for the logs.

**Comment by HamLaertes** [comment]
Okay, thanks for your remind! We will open a new issue.
