### ISSUE TITLE
DeepAttack-daqiezi-The compressed file is too large and the upload is terminated due to unstable network. Is there any solution?

### ISSUE THREAD

**Issue by HqingLiu** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#2]

**Comment by aisg-py** [comment]
Kindly follow the issue format stipulated in #1.

Please read through the submission guidelines in this GitHub repository carefully for important information on various restrictions, including the maximum uploadable compressed Docker image file.
 
Participants are responsible for their own submissions conforming to the submission guidelines, as well as ensuring that their network connection is sufficiently robust to handle their submission upload process.

**Comment by HqingLiu** [comment]
During the upload process, we were interrupted several times due to network connection problems and the submission was shown as failed, but this seems to have been miscalculated as one submission. Please help us update the recovery submission number.

**Comment by aisg-py** [comment]
As per Clause 15 of the Terms and Conditions, we do not reset the submission count due to issues related to participants' network connectivity. Thank you for your understanding.
