### ISSUE TITLE
[ModelCrackers] - [nonstop] - [API Question]

### ISSUE THREAD

**Issue by nonstopfor** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#24]
Can we call the APIs of multiple victim models simultaneously? For instance, if we invoke the APIs of two victim models at the same time, could this result in any errors or exceptions?

**Comment by nonstopfor** [comment]
I haven't found relevant descriptions in the README.

**Comment by aisg-py** [comment]
No. This has to be done sequentially.

**Comment by nonstopfor** [comment]
Thanks a lot~
