### ISSUE TITLE
[ModelCrackers] - [yangjunx21] - [log file request]

### ISSUE THREAD

**Issue by yangjunx21** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#29]
Hi, we kindly request the log file for our 5th submission (sub5.tar.gz),  as we have noticed a discrepancy between the ASR of this submission and our offline tests.

**Comment by aisg-py** [comment]
We would not be able to release this particular log file as this would compromise the hidden nature of the VLLM.
