### ISSUE TITLE
[ModelCrackers] - [yangjunx21] - [question about submission quota]

### ISSUE THREAD

**Issue by yangjunx21** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#32]
Hi, I have a question regarding the submission rules. If we made a submission on 2024-09-03 at 14:49:59, and we have now reached the limit of 7 submissions in 14 days. Could we get the quota refreshed exactly at 2024-09-17, 14:49:59 (14 days later), or is the refresh based on the start of a new calendar day (2024-09-17, 00:00:00)?

**Comment by aisg-py** [comment]
The submission limit is refreshed by on the start of a new calendar day.
