### ISSUE TITLE
 environment variable

### ISSUE THREAD

**Issue by wl71** [AISG-Technology-Team/GCSS-Track-1B-Submission-Guide#5]
for the latest sample_submission code , in run.sh , you use  GCSS_SERVER as variable name,

but in env_setup.py file you use  GCSS_SERVER_CONTAINER_NAME as variable name

# Environment Variables
GCSS_SERVER_CONTAINER_NAME = os.getenv(
    "GCSS_SERVER_CONTAINER_NAME", "vllm_server"
)

should I change code for env_setup.py.

I submitted one version, use above code, got SysError, is it because the variable name is not same ?

**Comment by aisg-py** [comment]
Please use the environment variable `GCSS_SERVER` that will be passed to your docker container and add in the relevant resource endpoint. The `GCSS_SERVER` should be in the following format `"http://xxxxx"`.

**Comment by wl71** [comment]
thanks
